<?php

// autoload-classmap.php @generated by Strauss

$vendorprefixed = dirname(__FILE__);

return array(
   'WPSWAP_EDD_SL_Plugin_Updater' => $vendorprefixed . '/webdevstudios/edd-sl-plugin-updater/EDD_SL_Plugin_Updater.php',
);